FROM restaurant-base

USER root

#COPY . /home/docker/orders/
COPY ./run.sh /home/docker/orders/run.sh
COPY ./wheelhouse /home/docker/orders/wheelhouse

WORKDIR /home/docker/orders

RUN apk add --no-cache postgresql-client \
	&& chmod +x /home/docker/orders/run.sh \
	&& chown -R docker:docker /home/docker

USER docker

RUN pipenv run  pip install --no-index -f /home/docker/orders/wheelhouse restaurant-orders \
    && rm -rf wheelhouse/

CMD pipenv run sh run.sh
